-- Get all the Movies List 

USE MAVENMOVIES;

SELECT * FROM RENTAL;

SELECT * FROM FILM;

SELECT * FROM INVENTORY;

SELECT * FROM PAYMENT;

SELECT * FROM CUSTOMER;

SELECT * FROM ADDRESS;

SELECT * FROM CITY;

SELECT * FROM COUNTRY;

SELECT * FROM LANGUAGE;

SELECT * FROM CATEGORY;

SELECT * FROM FILM_CATEGORY;

SELECT * FROM ACTOR;

SELECT * FROM FILM_ACTOR;

-- GET THE LIST OF CUSTOMERS AND THEIR EMAIL IDS

SELECT EMAIL,FIRST_NAME,LAST_NAME
FROM CUSTOMER;

-- GET THE LIST OF FIRST 10 CUSTOMERS AND THEIR EMAIL IDS

SELECT CUSTOMER_ID,EMAIL,FIRST_NAME,LAST_NAME
FROM CUSTOMER
LIMIT 10 OFFSET 2;