
USE MAVENMOVIES;

SELECT count(RENTAL_DATE)
FROM RENTAL;

SELECT SUM(AMOUNT) AS REVENUE
FROM PAYMENT;

SELECT ROUND(AVG(AMOUNT),2) AS AVG_RENTAL
FROM PAYMENT;

SELECT MAX(AMOUNT) AS REVENUE
FROM PAYMENT;

SELECT MIN(AMOUNT) AS REVENUE
FROM PAYMENT;

SELECT *
FROM PAYMENT
WHERE AMOUNT = 0;

SELECT RENTAL_ID,PAYMENT_ID,PAYMENT_DATE,AMOUNT
FROM PAYMENT;

SELECT PAYMENT_DATE,RENTAL_ID,PAYMENT_ID,PAYMENT_DATE,AMOUNT,CUSTOMER_ID,STAFF_ID,LAST_UPDATE
FROM PAYMENT;

SELECT * 
FROM PAYMENT
ORDER BY PAYMENT_DATE DESC
LIMIT 10;

SELECT * 
FROM PAYMENT
LIMIT 10 OFFSET 5;

SELECT (CONCAT(LEFT(FIRST_NAME,1),LOWER(SUBSTRING(FIRST_NAME,2))," ",LAST_NAME)) AS FULL_NAME, LOWER(EMAIL)
FROM CUSTOMER;

SELECT SUBSTRING(FIRST_NAME,2,2) FROM CUSTOMER;

SELECT (CONCAT(LEFT(FIRST_NAME,1),LOWER(SUBSTRING(FIRST_NAME,2))," ",LEFT(LAST_NAME,1),LOWER(SUBSTRING(LAST_NAME,2)))) AS FULL_NAME, 
LOWER(EMAIL) AS EMAIL_ID
FROM CUSTOMER;

-- CREATE A REPORT OF CUSTOMER ID 9 HAS EVER PURCHASED
SELECT *
FROM RENTAL
WHERE CUSTOMER_ID = 9;

-- CREATE A REPORT OF CUSTOMER ID 9 AND 10 HAS EVER PURCHASED
SELECT *
FROM RENTAL
WHERE CUSTOMER_ID = 9 OR CUSTOMER_ID = 10;

-- CREATE A REPORT OF CUSTOMER ID 9,10,11 HAS EVER PURCHASED

SELECT *
FROM RENTAL
WHERE CUSTOMER_ID = 9 OR CUSTOMER_ID = 10 OR CUSTOMER_ID = 11;

SELECT *
FROM RENTAL
WHERE CUSTOMER_ID IN (9,10,11);

SELECT *
FROM RENTAL
WHERE CUSTOMER_ID >= 9 AND CUSTOMER_ID <=11;

SELECT *
FROM RENTAL
WHERE CUSTOMER_ID BETWEEN 9 AND 11;

SELECT *
FROM FILM
WHERE SPECIAL_FEATURES = "Deleted Scenes";

SELECT *
FROM FILM
WHERE SPECIAL_FEATURES LIKE "%Deleted Scenes%";

-- 1. % - stands for 0 or more characters
-- 2. _ (underscore) - stands for 1 and only 1 character

-- Examples
-- LIKE “a%” - any length string starting with “a”
-- LIKE “%a” - anything length string with ends with “a”
-- LIKE “%em%” - any string with “em” in between, will match “em” also
-- LIKE “a_” - Any string with length 2 and starting from “a”
-- LIKE “a_%” - A string with starts from “a” and at least is 2 character long

SELECT *
FROM FILM
WHERE RATING LIKE "P%";

SELECT *
FROM ADDRESS
WHERE ADDRESS2 IS NULL OR TRIM(ADDRESS2) = "";

SELECT CITY_ID
FROM CITY
WHERE COUNTRY_ID = 44;

SELECT *
FROM ADDRESS
WHERE CITY_ID IN (SELECT CITY_ID
FROM CITY
WHERE COUNTRY_ID = 44);

-- SUBQUERIES

-- we want addresses of Indian Cities

SELECT *
FROM COUNTRY
WHERE COUNTRY = "India";

SELECT CITY_ID
FROM CITY
WHERE COUNTRY_ID = 44;

SELECT *
FROM ADDRESS
WHERE CITY_ID IN (SELECT CITY_ID
FROM CITY
WHERE COUNTRY_ID = 44);

SELECT *
FROM RENTAL;

SELECT *
FROM CUSTOMER
where address_id in (SELECT address_id
FROM ADDRESS
WHERE DISTRICT = "California");

SELECT address_id
FROM ADDRESS
WHERE DISTRICT = "California";

-- provide a list of customers staying in california district for offers

SELECT *
FROM ADDRESS
WHERE DISTRICT = "California";

-- CATEGORIZE MOVIES AS PER LENGTH

SELECT FILM_ID,TITLE,LENGTH,
CASE
	WHEN LENGTH < 60 THEN "UNDER 1 HR"
    WHEN LENGTH BETWEEN 60 AND 90 THEN "1 TO 1.5 HRS"
    WHEN LENGTH > 90 THEN "LONG MOVIES"
    ELSE "ERROR"
END AS LENGTH_BUCKET
FROM FILM;

SELECT FILM_ID,TITLE,LENGTH,IF(LENGTH < 60,"SHORT_FILM","LONG_FILM") AS FILM_LENGTH_CAT
FROM FILM;

SELECT FILM_ID,TITLE,LENGTH,
CASE
	WHEN LENGTH < 60 THEN "SHORT_FILM"
    ELSE "LONG_FILM"
END AS LENGTH_BUCKET
FROM FILM;

-- CATEGORIZING MOVIES TO RECOMMEND VARIOUS AGE GROUPS AND DEMOGRAPHIC

SELECT TITLE,DESCRIPTION,RENTAL_DURATION,RENTAL_RATE,LENGTH,RATING,
CASE
	WHEN RENTAL_DURATION <= 4 THEN "RENTAL TOO SHORT"
    WHEN RENTAL_RATE >= 3.99 THEN "TOO EXPENSIVE"
    WHEN RATING IN ("NC-17","R") THEN "TOO ADULT"
    WHEN LENGTH NOT BETWEEN 60 AND 90 THEN "TOO SHORT OR TOO LONG"
    WHEN DESCRIPTION LIKE "%Shark%" then "NO_NO_HAS_SHARKS"
    ELSE "GREAT RECOMMENDATION FOR CHILDREN"
END AS FIT_FOR_RECOMMENDATION
FROM FILM;



