
USE MAVENMOVIES;

SELECT count(RENTAL_DATE)
FROM RENTAL;

SELECT SUM(AMOUNT) AS REVENUE
FROM PAYMENT;

SELECT ROUND(AVG(AMOUNT),2) AS AVG_RENTAL
FROM PAYMENT;

SELECT MAX(AMOUNT) AS REVENUE
FROM PAYMENT;

SELECT MIN(AMOUNT) AS REVENUE
FROM PAYMENT;

SELECT COUNT(*)
FROM PAYMENT
WHERE AMOUNT = 0;

SELECT RENTAL_ID,PAYMENT_ID,PAYMENT_DATE,AMOUNT
FROM PAYMENT;

SELECT PAYMENT_DATE,RENTAL_ID,PAYMENT_ID,PAYMENT_DATE,AMOUNT,CUSTOMER_ID,STAFF_ID,LAST_UPDATE
FROM PAYMENT;

SELECT * 
FROM PAYMENT
ORDER BY PAYMENT_DATE DESC
LIMIT 10;